# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import coordinate_geometry_pb2 as coordinate__geometry__pb2


class CoordinateGeometryServiceStub(object):
  """Interface exported by the server
  Services for coordinate geometry system
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Magnitude = channel.unary_unary(
        '/coordinate_geometry.CoordinateGeometryService/Magnitude',
        request_serializer=coordinate__geometry__pb2.Point.SerializeToString,
        response_deserializer=coordinate__geometry__pb2.Distance.FromString,
        )
    self.CartesianDistance = channel.unary_unary(
        '/coordinate_geometry.CoordinateGeometryService/CartesianDistance',
        request_serializer=coordinate__geometry__pb2.LineSegment.SerializeToString,
        response_deserializer=coordinate__geometry__pb2.Distance.FromString,
        )


class CoordinateGeometryServiceServicer(object):
  """Interface exported by the server
  Services for coordinate geometry system
  """

  def Magnitude(self, request, context):
    """A Simple RPC

    Obtains the Magnitude of a given point
    Magnitude can also be defined as distance of given point
    from the origin
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CartesianDistance(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CoordinateGeometryServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Magnitude': grpc.unary_unary_rpc_method_handler(
          servicer.Magnitude,
          request_deserializer=coordinate__geometry__pb2.Point.FromString,
          response_serializer=coordinate__geometry__pb2.Distance.SerializeToString,
      ),
      'CartesianDistance': grpc.unary_unary_rpc_method_handler(
          servicer.CartesianDistance,
          request_deserializer=coordinate__geometry__pb2.LineSegment.FromString,
          response_serializer=coordinate__geometry__pb2.Distance.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'coordinate_geometry.CoordinateGeometryService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
