# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coordinate_geometry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='coordinate_geometry.proto',
  package='coordinate_geometry',
  syntax='proto3',
  serialized_pb=_b('\n\x19\x63oordinate_geometry.proto\x12\x13\x63oordinate_geometry\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"e\n\x0bLineSegment\x12*\n\x06point1\x18\x01 \x01(\x0b\x32\x1a.coordinate_geometry.Point\x12*\n\x06point2\x18\x02 \x01(\x0b\x32\x1a.coordinate_geometry.Point\"\x1c\n\x08\x44istance\x12\x10\n\x08\x64istance\x18\x01 \x01(\x02\x32\xbd\x01\n\x19\x43oordinateGeometryService\x12H\n\tMagnitude\x12\x1a.coordinate_geometry.Point\x1a\x1d.coordinate_geometry.Distance\"\x00\x12V\n\x11\x43\x61rtesianDistance\x12 .coordinate_geometry.LineSegment\x1a\x1d.coordinate_geometry.Distance\"\x00\x62\x06proto3')
)




_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='coordinate_geometry.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='coordinate_geometry.Point.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='coordinate_geometry.Point.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=79,
)


_LINESEGMENT = _descriptor.Descriptor(
  name='LineSegment',
  full_name='coordinate_geometry.LineSegment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='point1', full_name='coordinate_geometry.LineSegment.point1', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='point2', full_name='coordinate_geometry.LineSegment.point2', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=182,
)


_DISTANCE = _descriptor.Descriptor(
  name='Distance',
  full_name='coordinate_geometry.Distance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='distance', full_name='coordinate_geometry.Distance.distance', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=212,
)

_LINESEGMENT.fields_by_name['point1'].message_type = _POINT
_LINESEGMENT.fields_by_name['point2'].message_type = _POINT
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['LineSegment'] = _LINESEGMENT
DESCRIPTOR.message_types_by_name['Distance'] = _DISTANCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
  DESCRIPTOR = _POINT,
  __module__ = 'coordinate_geometry_pb2'
  # @@protoc_insertion_point(class_scope:coordinate_geometry.Point)
  ))
_sym_db.RegisterMessage(Point)

LineSegment = _reflection.GeneratedProtocolMessageType('LineSegment', (_message.Message,), dict(
  DESCRIPTOR = _LINESEGMENT,
  __module__ = 'coordinate_geometry_pb2'
  # @@protoc_insertion_point(class_scope:coordinate_geometry.LineSegment)
  ))
_sym_db.RegisterMessage(LineSegment)

Distance = _reflection.GeneratedProtocolMessageType('Distance', (_message.Message,), dict(
  DESCRIPTOR = _DISTANCE,
  __module__ = 'coordinate_geometry_pb2'
  # @@protoc_insertion_point(class_scope:coordinate_geometry.Distance)
  ))
_sym_db.RegisterMessage(Distance)



_COORDINATEGEOMETRYSERVICE = _descriptor.ServiceDescriptor(
  name='CoordinateGeometryService',
  full_name='coordinate_geometry.CoordinateGeometryService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=215,
  serialized_end=404,
  methods=[
  _descriptor.MethodDescriptor(
    name='Magnitude',
    full_name='coordinate_geometry.CoordinateGeometryService.Magnitude',
    index=0,
    containing_service=None,
    input_type=_POINT,
    output_type=_DISTANCE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CartesianDistance',
    full_name='coordinate_geometry.CoordinateGeometryService.CartesianDistance',
    index=1,
    containing_service=None,
    input_type=_LINESEGMENT,
    output_type=_DISTANCE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COORDINATEGEOMETRYSERVICE)

DESCRIPTOR.services_by_name['CoordinateGeometryService'] = _COORDINATEGEOMETRYSERVICE

# @@protoc_insertion_point(module_scope)
